### PR TITLE
Ding modelling for bioptim

### PR DESCRIPTION
**Pull request by Kev1CO**
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/Ding_Model/1)

### CODE REVIEW

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/Ding_Model/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Kev1CO)

___
*[`Bioptim_exemples/custom_package/custom_dynamics.py` line 64 at r2](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NOWfqTj--FqlRtCzwgc:-NOWfqTj--FqlRtCzwgd:bui7rmm) ([raw file](https://github.com/Ipuch/Ding_Model/blob/1fe08dbe30cb55d095eaf3ebbd9e9f1133019923/Bioptim_exemples/custom_package/custom_dynamics.py#L64)):*
> ```Python
> 
> def custom_configure_dynamics_function(ocp, nlp, **extra_params):
>     # todo : is it relevant to call **extra_params as all_ocp doesn't exists anymore (replace extra_params with t) ?
> ```

Yes. It's the default header.

**Comment by Kev1CO** [comment]
image

Pourquoi est-ce que mon contrôle est égale à 0x1 est pas à 0x0 comme précédemment ?
Que fait u_scale ? Car c’est la même chose

**Comment by Kev1CO** [comment]
image

Pas de contrôle alors pourquoi controltype Constant et pas controltype None ?

**Comment by Kev1CO** [comment]
image

A quoi sert le   image ?

**Comment by Kev1CO** [comment]
image

Lors de l’exécution de la continuité, dans notre cas de figure, sommes nous pas dans un multinode constraint car nous faisons du multinode shooting ?
self.multinode_constraint = False

**Comment by Kev1CO** [comment]
image

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/Ding_Model/1)* status: all files reviewed, 4 unresolved discussions (waiting on @Kev1CO)

___
*[`Bioptim_exemples/custom_package/custom_dynamics.py` line 64 at r2](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NOWfqTj--FqlRtCzwgc:-NP3uPN17wc5BNKyQGjK:b-pi9877) ([raw file](https://github.com/Ipuch/Ding_Model/blob/1fe08dbe30cb55d095eaf3ebbd9e9f1133019923/Bioptim_exemples/custom_package/custom_dynamics.py#L64)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Yes. It's the default header.
</blockquote></details>

remove todo
___
*[`Bioptim_exemples/custom_package/custom_dynamics.py` line 120 at r3](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NP3vlN1532gxziwLG46:-NP3vlN1532gxziwLG47:b9v9rzo) ([raw file](https://github.com/Ipuch/Ding_Model/blob/bd2f1b46bdbba01d551087edc9f6e4ed13b62d69/Bioptim_exemples/custom_package/custom_dynamics.py#L120)):*
> ```Python
>     """
>     configure_force(ocp, nlp, as_states=True, as_controls=False)
>     configure_ca_troponin_complex(ocp, nlp, as_states=True, as_controls=False)
> ```

reverse the order. if necessary.
___
*[`Bioptim_exemples/custom_package/custom_objectives.py` line 6 at r3](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NP3v2ic-4zUjLktFERU:-NP3v2ic-4zUjLktFERV:bi12wk4) ([raw file](https://github.com/Ipuch/Ding_Model/blob/bd2f1b46bdbba01d551087edc9f6e4ed13b62d69/Bioptim_exemples/custom_package/custom_objectives.py#L6)):*
> ```Python
> 
> 
> def track_muscle_force_custom(all_pn: PenaltyNodeList | list, force: int | float) -> MX:
> ```

Try MINIMIZE_STATE, target= XXX, key='f',
f = name of the variable.
___
*[`Bioptim_exemples/custom_package/custom_objectives.py` line 21 at r3](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NP3wDYc9KPaG6axPJ_1:-NP3wDYc9KPaG6axPJ_2:brrih5f) ([raw file](https://github.com/Ipuch/Ding_Model/blob/bd2f1b46bdbba01d551087edc9f6e4ed13b62d69/Bioptim_exemples/custom_package/custom_objectives.py#L21)):*
> ```Python
>     nlp = all_pn.nlp
>     current_force = nlp.states[0].cx
>     force_diff = (current_force - force) ** 2
> ```

remove the quadratic term and the target of the function
objective.add(MINIMIZE_XXXX,target=....,node=....,quadratic=True)

**Review by Kev1CO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Ipuch/Ding_Model/1)* status: all files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`Bioptim_exemples/custom_package/custom_dynamics.py` line 64 at r2](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NOWfqTj--FqlRtCzwgc:-NP4IMe6ACvJ3tbSXfWY:b-896fix) ([raw file](https://github.com/Ipuch/Ding_Model/blob/1fe08dbe30cb55d095eaf3ebbd9e9f1133019923/Bioptim_exemples/custom_package/custom_dynamics.py#L64)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove todo
</blockquote></details>

Done.
___
*[`Bioptim_exemples/custom_package/custom_dynamics.py` line 120 at r3](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NP3vlN1532gxziwLG46:-NP4Id4Q9rl4TRXyYvN6:b-896fix) ([raw file](https://github.com/Ipuch/Ding_Model/blob/bd2f1b46bdbba01d551087edc9f6e4ed13b62d69/Bioptim_exemples/custom_package/custom_dynamics.py#L120)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

reverse the order. if necessary.
</blockquote></details>

Done.
___
*[`Bioptim_exemples/custom_package/custom_objectives.py` line 6 at r3](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NP3v2ic-4zUjLktFERU:-NP4Je-o4flMYoPICvNC:b-896fix) ([raw file](https://github.com/Ipuch/Ding_Model/blob/bd2f1b46bdbba01d551087edc9f6e4ed13b62d69/Bioptim_exemples/custom_package/custom_objectives.py#L6)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Try MINIMIZE_STATE, target= XXX, key='f',
f = name of the variable.
</blockquote></details>

Done.
___
*[`Bioptim_exemples/custom_package/custom_objectives.py` line 21 at r3](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-NP3wDYc9KPaG6axPJ_1:-NP4Ihui0pW3ftgkjRdV:b-896fix) ([raw file](https://github.com/Ipuch/Ding_Model/blob/bd2f1b46bdbba01d551087edc9f6e4ed13b62d69/Bioptim_exemples/custom_package/custom_objectives.py#L21)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove the quadratic term and the target of the function
objective.add(MINIMIZE_XXXX,target=....,node=....,quadratic=True)
</blockquote></details>

Done.

**Review by Ipuch — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/Ding_Model/1#-:-NP57LxeB1g0c5NwVS9l:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Kev1CO)

**Review by Ipuch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Ipuch/Ding_Model/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Kev1CO)

**Comment by Ipuch** [comment]
You should now test your model to be sure you don't break anything :) @Kev1CO

**Pull request merged**
